import Head from "next/head";
import Layout from "../components/layout";

export default function Home({message}) {
  return (
    <Layout home>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{message}</p>
    </Layout>
  );
}

export function getStaticProps() {
  const message = "This is a message from getStaticProps function";
  return {
    props: { message },
  };
}
